### ISSUE TITLE
same state object keeps being added to state_list in self_play.self_play_and_save

### ISSUE THREAD

**Issue by burakbayramli** [sangyi92/alphago_zero#1]
In AlphagoZero/training/self_play.py self_play_and_save() function, there is a 

state_list.append(state)

This should be changed to 

state_list.append(state.copy())

Otherwise same object keeps being added, and once done, it will be the last state, so state_list is full of the last state when game play is over.

**Comment by sanghyunyi** [comment]
Thanks!! I fixed it
